name: 自动部署到 GitHub Pages

on:
  push:
    branches: ["main"] # 监听 main 分支的变动

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: 下载源码
        uses: actions/checkout@v4

      - name: 设置 Node.js 环境
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 安装依赖
        run: npm install

      - name: 打包项目
        run: npm run build

      - name: 配置 GitHub Pages
        uses: actions/configure-pages@v4

      - name: 上传打包产物
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist' # 指向 Vite 打包后的 dist 文件夹

      - name: 部署到 GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4